#!/bin/bash

title="prezentace"
echo "title?: "
read title

# ASSEMBLE BEAMER PROJECT DIR
echo "creating project directory ./$title"
mkdir "$title"
cd "$title"

mkdir include
mkdir templates

# PREPARE main.tex FILE
cat > main.tex << EOF
% main.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/beamer-prez 

\documentclass{beamer}
\usepackage{graphicx}
\usepackage{beamerfoils}
\usepackage[czech]{babel}

\usetheme{AnnArbor}
\usefonttheme{structurebold}
\usecolortheme{crane}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{headline}{}
\setbeamertemplate{footline}{}

\title{$title}
\author{https://github.com/tweetlol}
\date{}

\begin{document}

% TITLE FRAME
\begin{frame}
        \titlepage
\end{frame}

\include{templates/block-itemize-frame-template.tex}
\include{templates/1-picture-frame-template.tex}
\include{templates/2-picture-frame-template.tex}
\include{templates/text-frame-template.tex}

\end{document}
EOF

# PREPARE BEAMER TEMPLATE FILES
## ITEMIZE FRAME TEMPLATE
cat > templates/block-itemize-frame-template.tex << EOF
% itemize-frame-template.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/tree/main/beamer-prez

\begin{frame}
        \frametitle{templates/itemize-frame-template.tex}
	\begin{columns}[c]
		\begin{column}{0.5\textwidth}
                        \begin{block}{A block of plain text}
			some plain text here, perhaps a lot of plain text here to talk about in the upcoming bulleted list!
                        \end{block}
		\end{column}
		\begin{column}{0.5\textwidth}
			\begin{itemize}
                                \item<2-> item 2-
				\item<3-> item 3-
			\end{itemize}
		\end{column}
	\end{columns}
\end{frame}
EOF

## PICTURE FRAME TEMPLATEs
mkdir graphics
wget -O "graphics/example-graphic.jpg" https://picsum.photos/800/800 # downloads random exapmle-graphic
### 1 picture
cat > templates/1-picture-frame-template.tex << EOF
% 1-picture-frame-template.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/tree/main/beamer-prez

\begin{frame}
	\frametitle{templates/1-picture-frame-template.tex}
	\begin{columns}[c]
		\begin{column}{0.5\textwidth}
			\begin{itemize}
                                \item<1-> item 1-
				\item<2-> item 2-
			\end{itemize}
		\end{column}
		\begin{column}{0.5\textwidth}
			\centering
			\includegraphics[width=\textwidth]{graphics/example-graphic.jpg}
		\end{column}
	\end{columns}
\end{frame}
EOF

### 2 pictures
cat > templates/2-picture-frame-template.tex << EOF
% 2-picture-frame-template.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/tree/main/beamer-prez

\begin{frame}
	\frametitle{templates/2-picture-frame-template.tex}
	\begin{columns}[c]
		\begin{column}{0.5\textwidth}
			\centering
			\includegraphics[width=\textwidth]{graphics/example-graphic.jpg}
		\end{column}
		\begin{column}{0.5\textwidth}
			\centering
			\includegraphics[width=\textwidth]{graphics/example-graphic.jpg}
		\end{column}
	\end{columns}
\end{frame}
EOF

## TEXT FRAME TEMPLATE
cat > templates/text-frame-template.tex << EOF
% text-frame-template.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/tree/main/beamer-prez

\begin{frame}
        \frametitle{templates/text-frame-template.tex}
        Some plain text here as in for conclusion or whatnot. Thank you for your attention, subscribe share and like and subscribe.
\end{frame}
EOF

