#!/bin/bash

title="prezentace"
echo "title?: "
read title

# ASSEMBLE BEAMER PROJECT DIR
echo "creating project directory ./$title"
mkdir "$title"
cd "$title"

mkdir include
mkdir templates

# PREPARE main.tex FILE
cat > main.tex << EOF
% main.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/beamer-prez 

\documentclass{beamer}
\usepackage{graphicx}
\usepackage{beamerfoils}
\usepackage[czech]{babel}

\usefonttheme{structurebold}
\usetheme{AnnArbor}
\usecolortheme{crane}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{headline}{}
\setbeamertemplate{footline}{}

\title{$title}
\author{https://github.com/tweetlol}
\date{}

\begin{document}

% TITLE FRAME
\begin{frame}
        \titlepage
\end{frame}

\include{templates/block-itemize-frame-template.tex}
\include{templates/1-picture-frame-template.tex}
\include{templates/2-picture-frame-template.tex}
\include{templates/text-frame-template.tex}

\end{document}
EOF

# PREPARE BEAMER TEMPLATE FILES
## ITEMIZE FRAME TEMPLATE
cat > templates/block-itemize-frame-template.tex << EOF
% itemize-frame-template.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/beamer-prez 

\begin{frame}
        \frametitle{templates/itemize-frame-template.tex}
	\begin{columns}[c]
		\begin{column}{0.49\textwidth}
                        \begin{block}{A block of plain text}
			some plain text here, perhaps a lot of plain text here to talk about in the upcoming bulleted list!
                        \end{block}
		\end{column}
		\hfill
		\begin{column}{0.49\textwidth}
			\begin{itemize}
                \item Text of item 1
				\item Text of item 2
			\end{itemize}
		\end{column}
	\end{columns}
\end{frame}
EOF

## 1 PICTURE FRAME TEMPLATE
mkdir graphics
wget -O "graphics/example-graphic.jpg" https://picsum.photos/800/800 # downloads random exapmle-graphic
cat > templates/1-picture-frame-template.tex << EOF
% 1-picture-frame-template.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/beamer-prez 

\begin{frame}
	\frametitle{templates/1-picture-frame-template.tex}
	\begin{columns}[c]
		\begin{column}{0.49\textwidth}
			\begin{block}{Block 1 title}
				block 1 text
			\end{block}
			\begin{block}{Block 2 title}
				block 2 text
			\end{block}
		\end{column}
		\hfill
		\begin{column}{0.49\textwidth}
			\centering
			\includegraphics[width=\textwidth]{graphics/example-graphic.jpg}
		\end{column}
	\end{columns}
\end{frame}
EOF

## 2 PICTUREs FRAME TEMPLATE
cat > templates/2-picture-frame-template.tex << EOF
% 2-picture-frame-template.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/beamer-prez 

\begin{frame}
	\frametitle{templates/2-picture-frame-template.tex}
	\begin{columns}[c]
		\begin{column}{0.49\textwidth}
			\centering
			\includegraphics[width=\textwidth]{graphics/example-graphic.jpg}
		\end{column}
		\hfill
		\begin{column}{0.49\textwidth}
			\centering
			\includegraphics[width=\textwidth]{graphics/example-graphic.jpg}
		\end{column}
	\end{columns}
\end{frame}
EOF

## TEXT-BLOCK FRAME TEMPLATE
cat > templates/text-frame-template.tex << EOF
% text-frame-template.tex FILE GENERATED BY beamer-prez.sh
% https://github.com/tweetlol/scriptorium/beamer-prez 

\begin{frame}
        \frametitle{templates/text-frame-template.tex}
        \begin{block}{Block 1 title}
		Some plain Block 1 text here as in for conclusion or whatnot. Thank you for your attention, subscribe share and like and subscribe.
		\end{block}
\end{frame}
EOF

